---
# tasks file for ansible-role-teslamate

- name: Validating that required vars are set for the role
  assert:
    that:
      - fqdn_teslamate | length > 0
      - fqdn_grafana | length > 0
      - grafana_admin_username | length > 0
      - grafana_admin_password | length > 0
      - postgresql_database_username | length > 0
      - postgresql_database_password | length > 0
    fail_msg: ERROR! You have not setup the vars that are required! Please read the role-docs..
    success_msg: Check passed.. continuing!
    quiet: yes

- name: Creating folder {{ docker_compose_directory }} to be the directory of TeslaMate files, if it doesn't exist
  file:
    path: "{{ docker_compose_directory }}"
    state: directory

- name: Generating docker-compose.yml configuration file and placing in {{ docker_compose_directory }}
  template:
    src: docker-compose.yml.j2
    dest: "{{ docker_compose_directory }}/docker-compose.yml"

- name: Generating .env file and placing in {{ docker_compose_directory }}
  template:
    src: env.j2
    dest: "{{ docker_compose_directory }}/.env"

- name: Pulling latest version of TeslaMate
  docker_compose:
    project_src: {{ docker_compose_directory }}
    pull: yes
    debug: yes
  register: docker_compose_output_1

- name: Debugging of docker_compose_output_1 output
  debug:
    var: docker_compose_output_1

- name: Restarting docker containers of TeslaMate
  docker_compose:
    project_src: {{ docker_compose_directory }}
    state: present
    debug: yes
  register: docker_compose_output_2

- name: Debugging of docker_compose_output_1 output
  debug:
    var: docker_compose_output_2
